#!/usr/bin/env bash
#####该脚本用于删除本地分支。
# 用法介绍
# git delete feature1 
# git delete feature2 feature3

export COLOR_RED='\e[0;31m'
export COLOR_NC='\e[0m'
if [ $# -eq 0 ];then
    echo Sorry, branchName shouldn\'t be empty
    exit 1
fi

availableArr=
i=0
length=$#
while [ $i -lt $length ]
do
    branch=$1
    if [[ `git branch | grep "$branch"` ]]
    then
        availableArr[$i]=$branch
        git branch -D $branch
    fi
    i=`expr $i + 1`
    shift
done

save_ifs=$IFS
IFS=','
availableString="${availableArr[*]}"
if [ -n "$availableString" ];then
    echo -e Local branch: $COLOR_RED $availableString $COLOR_NC deleted successfully!
else 
    echo Not branch deleted!
fi

