#!/usr/bin/env bash
# Author: Jingwei Liu <liujingwei02@meituan.com>
# Last Modified: 水 26  3月 2014 05:52:42 午後
set -e

# show changed files in git cherry
if [[ -n $1 ]]; then
    upstream=$@
else
    upstream="master"
fi
git cherry $upstream | awk '{print $2}' | xargs git sh
