#!/usr/bin/env bash

git checkout master && git pull 
if [ "$1" ]; then
    git checkout $1
    if [ $? -gt 0 ];then
        git checkout -b $1
    fi
fi
currentBranch=$(git rev-parse --abbrev-ref HEAD)
echo You are at branch  $currentBranch
