#!/usr/bin/env bash
# Author: Jingwei Liu <liujingwei02@meituan.com>
# Last Modified: 火 18  3月 2014 01:16:39 午後
set -e

# squash commits before review
number=`git cherry origin/master | wc -l`

git rebase -i HEAD~$number
