#!/usr/bin/env bash
# Author: Jingwei Liu <liujingwei02@meituan.com>
# Last Modified: 水 26  3月 2014 05:52:42 午後
set -e

# show image directly inside nightly iTerm2
if [ $# -eq 0 ]; then
  echo "Usage: imgcat file ..."
  exit 1
fi
for fn in "$@"
do
  if [ -r $fn ] ; then
    printf '\033]1337;File=name='`echo -n "$fn" | base64`";"
    wc -c "$fn" | awk '{printf "size=%d",$1}'
    printf ";inline=1"
    printf ":"
    base64 < "$fn"
    printf '\a\n'
  else
    echo File $fn does not exist.
  fi
done
